/**
 * scripts/zoos-data.js — どうベビ 動物園マスターデータ
 *
 * 掲載動物園の営業情報・アクセス・アフィリエイトURLを一元管理します。
 *
 * 【追加・更新の手順】
 * 1. 新しい動物園を追加する場合、このファイルに1エントリ追加してください
 * 2. 掲載内容の修正依頼が来た場合、該当 zoo の値を更新するだけで全ページに反映されます
 * 3. 変更後は `npm run build` もしくは `node scripts/ssg.js` を実行
 *
 * 【スキーマ】
 *   slug            URL用スラッグ（半角英数・ハイフン）/zoos/{slug}/
 *   db_name         Supabase zoos.name と完全一致させる（赤ちゃんデータ突合用）
 *   name            表示用の動物園名
 *   prefecture      都道府県（都道府県別グルーピング用）
 *   city            市区町村
 *   address         郵便番号＋住所（全文）
 *   nearest_station 最寄り駅・アクセス情報（複数行可・改行で区切り）
 *   hours           営業時間（複数行可）
 *   closed_days     休園日
 *   fees            入園料（複数行可）
 *   description     動物園の特徴紹介（120〜200文字程度／SEO description 兼用）
 *   official_url    公式サイトURL
 *   asoview_url     アソビューアフィリエイトURL（null = 非表示・公式URLへ誘導）
 *   hero_emoji      ヒーロー絵文字（写真がない場合のフォールバック）
 */

export const ZOOS = [
  // ── 東京 ─────────────────────────────────────────────────────────────
  {
    slug: 'ueno',
    db_name: '上野動物園',
    name: '恩賜上野動物園',
    prefecture: '東京都',
    city: '台東区',
    address: '〒110-8711 東京都台東区上野公園9-83',
    nearest_station: 'JR上野駅・公園口から徒歩5分\n東京メトロ銀座線・日比谷線 上野駅から徒歩12分',
    hours: '9:30〜17:00（入園は16:00まで）',
    closed_days: '月曜日（祝日の場合は翌日）、年末年始（12/29〜1/1）',
    fees: '一般 600円／中学生 200円／65歳以上 300円／小学生以下 無料',
    description: 'ジャイアントパンダをはじめ約300種の動物を飼育する日本最古の動物園。双子パンダ「シャオシャオ」「レイレイ」で話題に。',
    official_url: 'https://www.tokyo-zoo.net/zoo/ueno/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F164335%2F',
    hero_emoji: '🐼',
  },
  {
    slug: 'tama',
    db_name: '多摩動物公園',
    name: '多摩動物公園',
    prefecture: '東京都',
    city: '日野市',
    address: '〒191-0042 東京都日野市程久保7-1-1',
    nearest_station: '京王線・多摩モノレール 多摩動物公園駅からすぐ',
    hours: '9:30〜17:00（入園は16:00まで）',
    closed_days: '水曜日（祝日の場合は翌日）、年末年始（12/29〜1/1）',
    fees: '一般 600円／中学生 200円／65歳以上 300円／小学生以下 無料',
    description: '52ヘクタールの広大な敷地で動物たちを自然に近い環境で観察できる動物園。ライオンバスやコアラ舎が人気。',
    official_url: 'https://www.tokyo-zoo.net/zoo/tama/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F164338%2F',
    hero_emoji: '🦁',
  },
  // ── 北海道 ───────────────────────────────────────────────────────────
  {
    slug: 'asahiyama',
    db_name: '旭山動物園',
    name: '旭川市旭山動物園',
    prefecture: '北海道',
    city: '旭川市',
    address: '〒078-8205 北海道旭川市東旭川町倉沼',
    nearest_station: 'JR旭川駅から旭川電気軌道バス「旭山動物園」行きで約40分',
    hours: '夏期 9:30〜17:15／冬期 10:30〜15:30（時期により変動）',
    closed_days: '年末年始、春・秋の閉園期間あり（公式サイト要確認）',
    fees: '大人 1,000円／中学生以下 無料',
    description: '動物の行動や生態をいきいきと見せる「行動展示」の先駆け。ペンギンの散歩やホッキョクグマ館が国内外から注目される。',
    official_url: 'https://www.city.asahikawa.hokkaido.jp/asahiyamazoo/',
    asoview_url: null,
    hero_emoji: '🐧',
  },
  {
    slug: 'maruyama',
    db_name: '札幌市円山動物園',
    name: '札幌市円山動物園',
    prefecture: '北海道',
    city: '札幌市',
    address: '〒064-0959 北海道札幌市中央区宮ヶ丘3-1',
    nearest_station: '地下鉄東西線「円山公園駅」からバスで約5分、徒歩約15分',
    hours: '3〜10月 9:30〜16:30／11〜2月 9:30〜16:00',
    closed_days: '第2・第4水曜日（4・11月のみ全水曜日）、年末年始',
    fees: '大人 800円／高校生 400円／中学生以下 無料',
    description: '北海道屈指の歴史ある動物園。ゾウやホッキョクグマなど寒冷地に適した動物たちの飼育環境が充実。',
    official_url: 'https://www.city.sapporo.jp/zoo/',
    asoview_url: null,
    hero_emoji: '🐻‍❄️',
  },
  // ── 神奈川 ───────────────────────────────────────────────────────────
  {
    slug: 'zoorasia',
    db_name: 'ズーラシア',
    name: 'よこはま動物園ズーラシア',
    prefecture: '神奈川県',
    city: '横浜市',
    address: '〒241-0001 神奈川県横浜市旭区上白根町1175-1',
    nearest_station: '相鉄線 鶴ヶ峰駅・三ツ境駅、JR 中山駅からバスで約15分',
    hours: '9:30〜16:30（入園は16:00まで）',
    closed_days: '火曜日（祝日の場合は翌日）、年末年始（12/29〜1/1）',
    fees: '大人 800円／高校生 300円／小中学生 200円／小学生未満 無料',
    description: '世界の気候帯・地域別に動物を配置した約45ヘクタールの動物園。オカピなど希少動物に会える。',
    official_url: 'https://www.hama-midorinokyokai.or.jp/zoo/zoorasia/',
    asoview_url: null,
    hero_emoji: '🦒',
  },
  // ── 愛知 ─────────────────────────────────────────────────────────────
  {
    slug: 'higashiyama',
    db_name: '東山動植物園',
    name: '東山動植物園',
    prefecture: '愛知県',
    city: '名古屋市',
    address: '〒464-0804 愛知県名古屋市千種区東山元町3-70',
    nearest_station: '地下鉄東山線「東山公園駅」から徒歩3分',
    hours: '9:00〜16:50（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合は直後の平日）、年末年始（12/29〜1/1）',
    fees: '大人 500円／中学生以下 無料',
    description: 'イケメンゴリラ「シャバーニ」で有名な、約500種の動物と約7,000種の植物を有する国内屈指の動植物園。',
    official_url: 'https://www.higashiyama.city.nagoya.jp/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F160839%2F',
    hero_emoji: '🦍',
  },
  // ── 大阪 ─────────────────────────────────────────────────────────────
  {
    slug: 'tennoji',
    db_name: '天王寺動物園',
    name: '天王寺動物園',
    prefecture: '大阪府',
    city: '大阪市',
    address: '〒543-0063 大阪府大阪市天王寺区茶臼山町1-108',
    nearest_station: '地下鉄御堂筋線・堺筋線「動物園前駅」「天王寺駅」から徒歩約10分',
    hours: '9:30〜17:00（5・9月の土日祝は18:00まで）',
    closed_days: '月曜日（祝日の場合は翌日）、年末年始（12/29〜1/1）',
    fees: '大人 500円／小中学生 200円／未就学児 無料',
    description: '1915年開園の大阪を代表する都市型動物園。約180種の動物が飼育され、アフリカサバンナゾーンが人気。',
    official_url: 'https://www.tennojizoo.jp/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F155400%2F',
    hero_emoji: '🦓',
  },
  // ── 兵庫 ─────────────────────────────────────────────────────────────
  {
    slug: 'kobe-oukoku',
    db_name: '神戸どうぶつ王国',
    name: '神戸どうぶつ王国',
    prefecture: '兵庫県',
    city: '神戸市',
    address: '〒650-0047 兵庫県神戸市中央区港島南町7-1-9',
    nearest_station: 'ポートライナー「計算科学センター（神戸どうぶつ王国・「富岳」前）駅」すぐ',
    hours: '平日 10:00〜16:00／土日祝 10:00〜17:00',
    closed_days: '木曜日（祝日・GW・春/夏/冬休みを除く）',
    fees: '大人 2,200円／小学生 1,200円／幼児（4・5歳）500円',
    description: '天候に左右されない全天候型動物園。動物との距離が近く、カピバラやハシビロコウの観察・ふれあいが楽しめる。',
    official_url: 'https://www.kobe-oukoku.com/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F151141%2F',
    hero_emoji: '🦦',
  },
  // ── 北海道（追加） ─────────────────────────────────────────────────
  {
    slug: 'kushiro',
    db_name: '釧路市動物園',
    name: '釧路市動物園',
    prefecture: '北海道',
    city: '釧路市',
    address: '〒085-0201 北海道釧路市阿寒町下仁々志別11',
    nearest_station: 'JR釧路駅から阿寒バスで約50分「釧路市動物園」下車',
    hours: '夏期 9:30〜16:30／冬期 10:00〜15:30',
    closed_days: '冬期は毎週水曜日、年末年始（12/30〜1/4）',
    fees: '大人 580円／高校生 230円／中学生以下 無料',
    description: '北海道最大級の規模を誇る動物園。アムールトラやホッキョクグマ、シロフクロウなど寒冷地の動物展示が充実。',
    official_url: 'https://www.city.kushiro.lg.jp/zoo/',
    asoview_url: null,
    hero_emoji: '🐅',
  },
  // ── 東北 ─────────────────────────────────────────────────────────────
  {
    slug: 'morioka-zoomo',
    db_name: '盛岡市動物公園',
    name: '盛岡市動物公園ZOOMO',
    prefecture: '岩手県',
    city: '盛岡市',
    address: '〒020-0803 岩手県盛岡市新庄字下八木田60-18',
    nearest_station: 'JR盛岡駅からバスで約30分',
    hours: '9:30〜16:30（時期により変動）',
    closed_days: '水曜日、12月〜3月の冬期休園',
    fees: '大人 800円／高校生以下 無料',
    description: '2023年リニューアルオープン。岩手の自然と動物をテーマに、ライオンやゾウなど約70種を飼育する東北の動物園。',
    official_url: 'https://zoomo.co.jp/',
    asoview_url: null,
    hero_emoji: '🦌',
  },
  {
    slug: 'yagiyama',
    db_name: '仙台市八木山動物公園',
    name: '仙台市八木山動物公園',
    prefecture: '宮城県',
    city: '仙台市',
    address: '〒982-0819 宮城県仙台市太白区八木山本町1-43',
    nearest_station: '地下鉄東西線「八木山動物公園駅」からすぐ',
    hours: '9:00〜16:45（11〜2月は16:00まで）',
    closed_days: '月曜日（祝日の場合は翌日）、年末年始',
    fees: '一般 480円／小中学生 120円／未就学児 無料',
    description: '東北最大級の動物園。アフリカ園・猛獣舎・ふれあい広場など、約140種の動物を飼育する。',
    official_url: 'https://www.city.sendai.jp/zoo/',
    asoview_url: null,
    hero_emoji: '🦁',
  },
  // ── 茨城・栃木・群馬 ─────────────────────────────────────────────────
  {
    slug: 'kamine',
    db_name: '日立市かみね動物園',
    name: '日立市かみね動物園',
    prefecture: '茨城県',
    city: '日立市',
    address: '〒317-0055 茨城県日立市宮田町5-2-22',
    nearest_station: 'JR日立駅から茨城交通バスで約10分',
    hours: '9:00〜17:00（11〜2月は16:15まで）',
    closed_days: '年中無休',
    fees: '大人 520円／小中学生 100円／未就学児 無料',
    description: '太平洋を望む丘の上にある動物園。チンパンジーやキリン、レッサーパンダなど約80種を展示。',
    official_url: 'https://www.city.hitachi.lg.jp/zoo/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F159908%2F',
    hero_emoji: '🦒',
  },
  {
    slug: 'utsunomiya-zoo',
    db_name: '宇都宮動物園',
    name: '宇都宮動物園',
    prefecture: '栃木県',
    city: '宇都宮市',
    address: '〒321-2114 栃木県宇都宮市上金井町552-2',
    nearest_station: 'JR宇都宮駅から車で約30分、関東自動車バスで「上金井」下車',
    hours: '9:00〜17:00（12〜2月は16:30まで）',
    closed_days: '年中無休',
    fees: '大人 1,400円／3歳〜小学生 700円',
    description: '遊園地併設の民営動物園。ホワイトタイガーやキリン、ライオンへの餌やり体験が人気。',
    official_url: 'https://utsunomiya-zoo.com/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F150798%2F',
    hero_emoji: '🐯',
  },
  {
    slug: 'nasu-oukoku',
    db_name: '那須どうぶつ王国',
    name: '那須どうぶつ王国',
    prefecture: '栃木県',
    city: '那須郡那須町',
    address: '〒329-3223 栃木県那須郡那須町大島1042-1',
    nearest_station: 'JR黒磯駅から車で約30分',
    hours: '平日 10:00〜16:30／土日祝 9:00〜17:00（時期により変動）',
    closed_days: '水曜日（時期により無休、要公式確認）',
    fees: '大人 2,600円／3歳〜小学生 1,200円',
    description: '「王国タウン」と「王国ファーム」の2エリア構成。カピバラ・ハシビロコウ・スナネコなど希少動物との距離が近い。',
    official_url: 'https://www.nasu-oukoku.com/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F150443%2F',
    hero_emoji: '🦫',
  },
  {
    slug: 'gunma-safari',
    db_name: '群馬サファリパーク',
    name: '群馬サファリパーク',
    prefecture: '群馬県',
    city: '富岡市',
    address: '〒370-2321 群馬県富岡市岡本1',
    nearest_station: '上信電鉄「上州富岡駅」から車で約15分',
    hours: '9:30〜16:30（3〜10月）／9:30〜16:00（11〜2月）',
    closed_days: '水曜日（祝日・GW・春夏冬休みを除く）',
    fees: '大人 2,800円／3歳〜中学生 1,400円',
    description: '車で園内を巡るサファリ形式の動物園。ライオン・ホワイトタイガー・ゾウなどを自然に近い環境で観察できる。',
    official_url: 'https://www.safari.co.jp/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F154783%2F',
    hero_emoji: '🐆',
  },
  // ── 埼玉・千葉 ──────────────────────────────────────────────
  {
    slug: 'saitama-kodomo',
    db_name: '埼玉県こども動物自然公園',
    name: '埼玉県こども動物自然公園',
    prefecture: '埼玉県',
    city: '東松山市',
    address: '〒355-0065 埼玉県東松山市岩殿554',
    nearest_station: '東武東上線「高坂駅」から西口バス5分',
    hours: '9:30〜17:00（3〜10月）／9:30〜16:00（11〜2月）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 710円／65歳以上 350円／中学生以下無料',
    description: 'コアラの飼育数が日本一。ニホンコウノトリなど希少種の保全にも取り組む自然豊かな動物園。',
    official_url: 'https://www.pref.saitama.lg.jp/saitamachildren-zoo/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F163051%2F',
    hero_emoji: '🐨',
  },
  {
    slug: 'omiya-koen',
    db_name: '大宮公園小動物園',
    name: '大宮公園小動物園',
    prefecture: '埼玉県',
    city: 'さいたま市',
    address: '〒330-0803 埼玉県さいたま市大宮区高鼻町4-156',
    nearest_station: '東武野田線「大宮公園駅」徒歩5分',
    hours: '9:30〜16:30',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '無料',
    description: '大宮公園内に位置する無料の動物園。レッサーパンダやリスザル、ミナミコアリクイなどを飼育。',
    official_url: 'https://www.pref.saitama.lg.jp/omiyakoen-zoo/',
    asoview_url: null,
    hero_emoji: '🦁',
  },
  {
    slug: 'chiba-zoo',
    db_name: '千葉市動物公園',
    name: '千葉市動物公園',
    prefecture: '千葉県',
    city: '千葉市',
    address: '〒264-0037 千葉県千葉市若葉区源町280',
    nearest_station: '千葉都市モノレール「動物公園駅」下車すぐ',
    hours: '9:30〜16:30（12〜2月は16:00まで）',
    closed_days: '水曜日（祝日の場合翌日）・年末年始',
    fees: '大人 700円／65歳以上 350円／中学生以下無料',
    description: '約150種1,100点の動物を飼育。レッサーパンダ「風太」で知られ、アフリカゾウ・ライオン・フラミンゴなど多彩な動物が揃う。',
    official_url: 'https://www.city-zoo.chiba.jp/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F159690%2F',
    hero_emoji: '🐘',
  },
  {
    slug: 'ichikawa',
    db_name: '市川市動植物園',
    name: '市川市動植物園',
    prefecture: '千葉県',
    city: '市川市',
    address: '〒272-0801 千葉県市川市大町284-1',
    nearest_station: 'JR武蔵野線「市川大野駅」徒歩約20分 / バス利用可',
    hours: '9:30〜16:30（11〜3月は16:00まで）',
    closed_days: '水曜日（祝日の場合翌日）・年末年始',
    fees: '大人 520円／小中学生 100円',
    description: '動物園と植物園が一体となった施設。ニホンザルの群れやレッサーパンダ、ダチョウなどが人気。',
    official_url: 'https://www.city.ichikawa.lg.jp/zoo/',
    asoview_url: null,
    hero_emoji: '🌿',
  },
  // ── 東京（追加）・神奈川 ────────────────────────────────────
  {
    slug: 'inokashira',
    db_name: '井の頭自然文化園',
    name: '井の頭自然文化園',
    prefecture: '東京都',
    city: '武蔵野市',
    address: '〒180-0005 東京都武蔵野市御殿山1-17-6',
    nearest_station: 'JR・京王「吉祥寺駅」徒歩約15分',
    hours: '9:30〜17:00（入園は16:00まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 400円／65歳以上 200円／中学生 150円',
    description: '都内唯一のゾウ「はな子」で知られた歴史ある動物園。現在もモルモット・リス・水生物を中心に展示。',
    official_url: 'https://www.tokyo-zoo.net/zoo/ino/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F164336%2F',
    hero_emoji: '🦦',
  },
  {
    slug: 'hamura',
    db_name: '羽村市動物公園',
    name: '羽村市動物公園',
    prefecture: '東京都',
    city: '羽村市',
    address: '〒205-0012 東京都羽村市羽東3-28-1',
    nearest_station: 'JR青梅線「羽村駅」徒歩約20分',
    hours: '9:30〜16:30（入園は16:00まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 630円／65歳以上 320円／小学生 無料',
    description: 'レッサーパンダやカピバラ・チンパンジーなどを飼育。子ども向けのふれあい広場が充実した市立動物公園。',
    official_url: 'https://www.city.hamura.tokyo.jp/zoo/',
    asoview_url: null,
    hero_emoji: '🦊',
  },
  {
    slug: 'adachi-bio',
    db_name: '生物園（足立区生物園）',
    name: '足立区生物園',
    prefecture: '東京都',
    city: '足立区',
    address: '〒123-0841 東京都足立区保木間2-17-1',
    nearest_station: '東武バス「生物園」下車すぐ',
    hours: '9:30〜17:00（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 300円／小中学生 150円',
    description: '昆虫・水生生物を中心に展示する個性的な施設。チョウが飛ぶ温室「バタフライガーデン」が人気。',
    official_url: 'https://www.adachiku.ed.jp/seibutsuen/',
    asoview_url: null,
    hero_emoji: '🦋',
  },
  {
    slug: 'nogeyama',
    db_name: '野毛山動物園',
    name: '横浜市立野毛山動物園',
    prefecture: '神奈川県',
    city: '横浜市',
    address: '〒220-0032 神奈川県横浜市西区老松町63-10',
    nearest_station: 'JR・市営地下鉄「桜木町駅」徒歩約15分',
    hours: '9:30〜16:30（入園は16:00まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '無料',
    description: '無料で入れる横浜の市立動物園。キリン・ライオン・ホッキョクグマなど大型動物を多数飼育。',
    official_url: 'https://www.hama-midorinokyokai.or.jp/zoo/nogeyama/',
    asoview_url: null,
    hero_emoji: '🦒',
  },
  {
    slug: 'kanazawa-zoo',
    db_name: '金沢動物園',
    name: '横浜市立金沢動物園',
    prefecture: '神奈川県',
    city: '横浜市',
    address: '〒236-0042 神奈川県横浜市金沢区釜利谷東5-15-1',
    nearest_station: '京急「金沢文庫駅」西口バス約10分',
    hours: '9:30〜16:30（入園は16:00まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 500円／65歳以上 250円／中学生以下無料',
    description: '有蹄類（ウシ・シカの仲間）を中心に展示。コアラ・オランウータン・アフリカゾウも飼育する丘陵の動物園。',
    official_url: 'https://www.hama-midorinokyokai.or.jp/zoo/kanazawa/',
    asoview_url: null,
    hero_emoji: '🦏',
  },
  // ── 静岡 ────────────────────────────────────────────────────
  {
    slug: 'fuji-safari',
    db_name: 'フジサファリパーク',
    name: 'フジサファリパーク',
    prefecture: '静岡県',
    city: '裾野市',
    address: '〒410-1231 静岡県裾野市須山字藤原2255-27',
    nearest_station: 'JR御殿場線「裾野駅」から車で約20分',
    hours: '9:00〜16:30（季節変動あり）',
    closed_days: '無休（メンテナンス休業あり）',
    fees: '大人 2,800円／小学生 1,400円／3〜5歳 700円',
    description: '富士山麓に広がる大型サファリパーク。バスや自家用車で草食・肉食獣ゾーンを周遊できる。',
    official_url: 'https://www.fujisafari.co.jp/',
    asoview_url: 'https://www.asoview.com/item/ticket/act0000023813/',
    hero_emoji: '🦁',
  },
  {
    slug: 'nihondaira',
    db_name: '日本平動物園',
    name: '静岡市立日本平動物園',
    prefecture: '静岡県',
    city: '静岡市',
    address: '〒422-8005 静岡県静岡市駿河区池田1767-6',
    nearest_station: 'JR「静岡駅」北口バス約40分',
    hours: '9:00〜16:30（入園は16:00まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 620円／小中学生 100円／未就学児無料',
    description: 'ホッキョクグマ・ライオン・アジアゾウなど大型動物を多数飼育。眺望の良い高台に位置する。',
    official_url: 'https://www.nhdzoo.jp/',
    asoview_url: null,
    hero_emoji: '🐻‍❄️',
  },
  {
    slug: 'hamamatsu-zoo',
    db_name: '浜松市動物園',
    name: '浜松市動物園',
    prefecture: '静岡県',
    city: '浜松市',
    address: '〒432-8006 静岡県浜松市中央区舘山寺町199',
    nearest_station: 'JR「浜松駅」バス約45分（舘山寺口下車）',
    hours: '9:00〜16:30（入園は16:00まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 500円／小中学生 50円／未就学児無料',
    description: '浜名湖畔に位置するアットホームな動物園。チンパンジー・ゴリラ・シロクマなど約130種を飼育。',
    official_url: 'https://www.hamazoo.net/',
    asoview_url: null,
    hero_emoji: '🦍',
  },
  {
    slug: 'izu-animal',
    db_name: '伊豆アニマルキングダム',
    name: '伊豆アニマルキングダム',
    prefecture: '静岡県',
    city: '東伊豆町',
    address: '〒413-0411 静岡県賀茂郡東伊豆町稲取3344',
    nearest_station: 'JR伊東線「伊豆稲取駅」から車で約5分',
    hours: '9:30〜17:00（冬期変動あり）',
    closed_days: '無休',
    fees: '大人 2,400円／小学生 1,400円／3〜5歳 500円',
    description: 'サバンナ式ふれあい動物園。カバ・シマウマ・チーターなどアフリカ動物と間近で触れ合える。',
    official_url: 'https://www.izu-ak.com/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F150150%2F',
    hero_emoji: '🦓',
  },
  // ── 愛知・石川・富山 ─────────────────────────────────────────
  {
    slug: 'nonhoi',
    db_name: 'のんほいパーク',
    name: 'のんほいパーク（豊橋総合動植物公園）',
    prefecture: '愛知県',
    city: '豊橋市',
    address: '〒441-8151 愛知県豊橋市大岩町字大穴1-238',
    nearest_station: 'JR「豊橋駅」バス約25分',
    hours: '9:00〜16:30（入園は16:00まで）',
    closed_days: '木曜日（祝日の場合翌日）・年末年始',
    fees: '大人 700円／小中学生 100円／未就学児無料',
    description: '動物園・植物園・自然史博物館・遊園地が一体の複合施設。アフリカゾウや希少な白いゴリラを飼育。',
    official_url: 'https://www.nonhoi.jp/',
    asoview_url: null,
    hero_emoji: '🌸',
  },
  {
    slug: 'jmc',
    db_name: '東山動植物園',
    name: '名古屋市東山動植物園',
    prefecture: '愛知県',
    city: '名古屋市',
    address: '〒464-0804 愛知県名古屋市千種区東山元町3-70',
    nearest_station: '名古屋市営地下鉄東山線「東山公園駅」3番出口すぐ',
    hours: '9:00〜16:50（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 500円／中学生以下無料',
    description: '日本最多水準の動物種数を誇る国内最大規模の動物園。コアラ・ホッキョクグマ・ユキヒョウなどを飼育。',
    official_url: 'https://www.higashiyama.city.nagoya.jp/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F160839%2F',
    hero_emoji: '🐨',
  },
  {
    slug: 'ishikawa-zoo',
    db_name: '石川県立いしかわ動物園',
    name: 'いしかわ動物園',
    prefecture: '石川県',
    city: '能美市',
    address: '〒923-0812 石川県能美市徳山町ホ60',
    nearest_station: 'JR「小松駅」バス約30分',
    hours: '9:00〜17:00（11〜3月は16:30まで）',
    closed_days: '火曜日（祝日の場合翌日）・年末年始',
    fees: '大人 700円／小中学生 200円',
    description: 'スマトラトラ・ジャガー・ニシゴリラなど希少な肉食獣を多数飼育。白山を望む自然豊かな動物園。',
    official_url: 'https://www.ishikawazoo.jp/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F164250%2F',
    hero_emoji: '🐅',
  },
  {
    slug: 'toyama-family',
    db_name: '富山市ファミリーパーク',
    name: '富山市ファミリーパーク',
    prefecture: '富山県',
    city: '富山市',
    address: '〒930-1154 富山県富山市古沢254',
    nearest_station: 'JR「富山駅」バス約35分',
    hours: '9:00〜16:30（入園は16:00まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 500円／小中学生 100円／未就学児無料',
    description: '立山連峰を背景に、ライオン・キリン・カバなどを飼育。日本の動物コーナーでは希少種も展示。',
    official_url: 'https://www.toyama-familypark.jp/',
    asoview_url: null,
    hero_emoji: '🦁',
  },
  // ── 近畿 ────────────────────────────────────────────────────
  {
    slug: 'kyoto-zoo',
    db_name: '京都市動物園',
    name: '京都市動物園',
    prefecture: '京都府',
    city: '京都市',
    address: '〒606-8333 京都府京都市左京区岡崎法勝寺町岡崎公園内',
    nearest_station: '地下鉄東西線「蹴上駅」徒歩約10分',
    hours: '9:00〜17:00（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 750円／中学生以下無料',
    description: '日本で2番目に古い動物園。ゴリラ・ニシキヘビ・コビトカバなど多彩な動物を、自然に近い環境で展示。',
    official_url: 'https://www5.city.kyoto.jp/zoo/',
    asoview_url: null,
    hero_emoji: '🦍',
  },
  {
    slug: 'oji',
    db_name: '王子動物園',
    name: '神戸市立王子動物園',
    prefecture: '兵庫県',
    city: '神戸市',
    address: '〒657-0838 兵庫県神戸市灘区王子町3-1',
    nearest_station: 'JR・阪急「灘駅」徒歩約10分',
    hours: '9:00〜17:00（入園は16:30まで）',
    closed_days: '水曜日（祝日の場合翌日）・年末年始',
    fees: '大人 600円／65歳以上 300円／中学生以下無料',
    description: '西日本唯一のジャイアントパンダ（タンタン）を飼育。コアラ・ホッキョクグマなど約130種を展示。',
    official_url: 'https://www.city.kobe.lg.jp/oji-zoo/',
    asoview_url: null,
    hero_emoji: '🐼',
  },
  {
    slug: 'himeji-zoo',
    db_name: '姫路市立動物園',
    name: '姫路市立動物園',
    prefecture: '兵庫県',
    city: '姫路市',
    address: '〒670-0012 兵庫県姫路市本町68（姫路城内）',
    nearest_station: 'JR・山陽「姫路駅」徒歩約30分',
    hours: '9:00〜17:00（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 210円／小中学生 50円',
    description: '姫路城の敷地内に位置する歴史ある動物園。チンパンジー・ライオン・キリンなどを身近に見られる。',
    official_url: 'https://www.city.himeji.lg.jp/zoo/',
    asoview_url: null,
    hero_emoji: '🏯',
  },
  {
    slug: 'adventure-world',
    db_name: 'アドベンチャーワールド',
    name: 'アドベンチャーワールド',
    prefecture: '和歌山県',
    city: '白浜町',
    address: '〒649-2201 和歌山県西牟婁郡白浜町堅田2399',
    nearest_station: 'JR「白浜駅」から無料シャトルバス約10分',
    hours: '10:00〜17:00（季節変動あり）',
    closed_days: '水曜日（季節により変動あり）',
    fees: '大人 5,300円／小学生 3,800円／4〜5歳 2,500円',
    description: '世界最多のジャイアントパンダ繁殖数を誇る施設。サファリ・水族館・ショーを併設するリゾート型動物園。',
    official_url: 'https://www.aws-s.com/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F164046%2F',
    hero_emoji: '🐼',
  },
  {
    slug: 'nara-deer',
    db_name: '奈良市ならまちにぎわい動物公園',
    name: '奈良市ならまちにぎわい動物公園',
    prefecture: '奈良県',
    city: '奈良市',
    address: '〒630-8303 奈良県奈良市今辻子町31-1',
    nearest_station: 'JR・近鉄「奈良駅」徒歩約20分',
    hours: '9:00〜17:00（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '無料',
    description: 'ヤギ・ウサギ・カピバラなどとふれあえる小規模な動物公園。奈良町観光と組み合わせて楽しめる。',
    official_url: 'https://www.city.nara.lg.jp/',
    asoview_url: null,
    hero_emoji: '🦌',
  },
  // ── 中国・四国 ──────────────────────────────────────────────
  {
    slug: 'ikeda-zoo',
    db_name: '池田動物園',
    name: '池田動物園',
    prefecture: '岡山県',
    city: '岡山市',
    address: '〒700-0942 岡山県岡山市北区京山2-5-1',
    nearest_station: 'JR「岡山駅」バス約20分',
    hours: '9:00〜17:00（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 800円／子ども（小〜高）300円／未就学児無料',
    description: '岡山市街を一望する丘上の動物園。ライオン・チーター・カバなど大型動物を約70種飼育。',
    official_url: 'https://www.ikedazoo.jp/',
    asoview_url: null,
    hero_emoji: '🦁',
  },
  {
    slug: 'asa',
    db_name: '広島市安佐動物公園',
    name: '広島市安佐動物公園',
    prefecture: '広島県',
    city: '広島市',
    address: '〒731-3355 広島県広島市安佐北区安佐町大字動物園',
    nearest_station: 'JR「可部線」「安芸亀山駅」から広電バス約20分',
    hours: '9:00〜17:00（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 510円／小中学生 30円',
    description: 'ミナミコアリクイ・アフリカゾウ・スマトラトラなどを飼育。動物の生態を重視した展示が評判。',
    official_url: 'https://www.asazoo.jp/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F164174%2F',
    hero_emoji: '🐘',
  },
  {
    slug: 'tokushima-zoo',
    db_name: '徳島市立富田動物園',
    name: '徳島市立富田動物園',
    prefecture: '徳島県',
    city: '徳島市',
    address: '〒770-0866 徳島県徳島市末広4-1-58',
    nearest_station: 'JR「徳島駅」バス約15分',
    hours: '9:00〜16:30（入園は16:00まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '無料',
    description: '入場無料の市立動物園。ライオン・ヒョウ・チンパンジー・キリンなど約70種を飼育。',
    official_url: 'https://www.city.tokushima.tokushima.jp/',
    asoview_url: null,
    hero_emoji: '🦒',
  },
  {
    slug: 'tobe',
    db_name: '愛媛県立とべ動物園',
    name: '愛媛県立とべ動物園',
    prefecture: '愛媛県',
    city: '伊予郡砥部町',
    address: '〒791-2191 愛媛県伊予郡砥部町上原町240',
    nearest_station: 'JR「松山駅」バス約40分',
    hours: '9:00〜17:00（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 500円／小中学生 100円／未就学児無料',
    description: 'ニシゴリラ・ポーラーベア・アムールトラなど約170種を飼育。展示の工夫が評価される四国最大の動物園。',
    official_url: 'https://www.tobezoo.com/',
    asoview_url: null,
    hero_emoji: '🦍',
  },
  {
    slug: 'noichi',
    db_name: 'のいち動物公園',
    name: 'のいち動物公園',
    prefecture: '高知県',
    city: '香南市',
    address: '〒781-5233 高知県香南市野市町大谷738',
    nearest_station: 'JR土讃線「のいち駅」徒歩約10分',
    hours: '9:30〜17:00（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 470円／小中学生 無料',
    description: 'ウォークスルー式サル舎やアジアゾウの屋外展示が特徴。テナガザル・マレーバクなど希少種も飼育。',
    official_url: 'https://www.noichizoo.or.jp/',
    asoview_url: null,
    hero_emoji: '🐒',
  },
  // ── 九州北部 ─────────────────────────────────────────────────
  {
    slug: 'fukuoka-zoo',
    db_name: '福岡市動物園',
    name: '福岡市動物園',
    prefecture: '福岡県',
    city: '福岡市',
    address: '〒810-0021 福岡県福岡市中央区南公園1-1',
    nearest_station: '市営地下鉄七隈線「薬院大通駅」徒歩約15分',
    hours: '9:00〜17:00（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 600円／中学生 200円／小学生以下無料',
    description: 'アフリカゾウ・スマトラトラ・ゴリラなど約130種を飼育。舎山公園内の緑豊かな市立動物園。',
    official_url: 'https://zoo.city.fukuoka.lg.jp/',
    asoview_url: null,
    hero_emoji: '🐘',
  },
  {
    slug: 'itozu',
    db_name: '北九州市いのちのたび博物館（自然史・歴史博物館）',
    name: 'スペースワールド跡地 → いのちのたび博物館',
    prefecture: '福岡県',
    city: '北九州市',
    address: '〒805-0071 福岡県北九州市八幡東区東田2-4-1',
    nearest_station: 'JR鹿児島本線「スペースワールド駅」徒歩3分',
    hours: '9:00〜17:00（入館は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 600円／中高生 360円／小学生 240円',
    description: '生物の進化を体感できる博物館。恐竜の実物大骨格標本やアミューズメントエリアも備える。',
    official_url: 'https://www.kmnh.jp/',
    asoview_url: null,
    hero_emoji: '🦕',
  },
  {
    slug: 'omuta-zoo',
    db_name: '大牟田市動物園',
    name: '大牟田市動物園',
    prefecture: '福岡県',
    city: '大牟田市',
    address: '〒836-0015 福岡県大牟田市大字岬1765-1',
    nearest_station: 'JR「大牟田駅」バス約15分',
    hours: '9:00〜17:00（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 310円／小中学生 100円',
    description: 'チンパンジーの文化的行動伝達研究で世界的に有名。チンパンジーの「芋洗い行動」の継承が観察される。',
    official_url: 'https://www.omutacity-zoo.jp/',
    asoview_url: null,
    hero_emoji: '🦧',
  },
  {
    slug: 'bio-park',
    db_name: '長崎バイオパーク',
    name: '長崎バイオパーク',
    prefecture: '長崎県',
    city: '西海市',
    address: '〒857-2317 長崎県西海市西彼町中山郷2291-1',
    nearest_station: 'JR「長崎駅」バス約90分（または車で約70分）',
    hours: '10:00〜17:00（入園は16:30まで）',
    closed_days: '無休',
    fees: '大人 1,850円／小中学生 930円',
    description: '放し飼いのカバ・フラミンゴ・アリクイなどと自由に触れ合える自然派動物園。餌やり体験が充実。',
    official_url: 'https://www.biopark.co.jp/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F156242%2F',
    hero_emoji: '🦛',
  },
  // ── 九州南部・沖縄 ──────────────────────────────────────────
  {
    slug: 'kumamoto-zoo',
    db_name: '熊本市動植物園',
    name: '熊本市動植物園',
    prefecture: '熊本県',
    city: '熊本市',
    address: '〒862-0911 熊本県熊本市東区健軍5-14-2',
    nearest_station: '熊本市電「動植物園入口」下車すぐ',
    hours: '9:00〜17:00（入園は16:30まで）',
    closed_days: '月曜日（祝日の場合翌日）・年末年始',
    fees: '大人 400円／小中学生 100円',
    description: 'ゾウ・ライオン・オランウータンなど多彩な動物に加え、植物園も併設する複合施設。',
    official_url: 'https://www.city.kumamoto.jp/zoo/',
    asoview_url: null,
    hero_emoji: '🌺',
  },
  {
    slug: 'african-safari',
    db_name: 'アフリカンサファリ',
    name: 'アフリカンサファリ（九州自然動物公園）',
    prefecture: '大分県',
    city: '宇佐市',
    address: '〒872-0101 大分県宇佐市安心院町南畑2291-1',
    nearest_station: 'JR日豊本線「柳ヶ浦駅」から車で約25分',
    hours: '9:00〜17:00（季節変動あり）',
    closed_days: '無休（悪天候時は変動あり）',
    fees: '大人 2,800円／小学生 1,400円／4歳〜 800円',
    description: '自家用車やバスでライオン・ゾウ・クマなどを間近に見られる九州最大規模のサファリパーク。',
    official_url: 'https://www.africansafari.co.jp/',
    asoview_url: 'https://www.asoview.com/item/ticket/act0000023815/',
    hero_emoji: '🦁',
  },
  {
    slug: 'miyazaki-phoenix',
    db_name: '宮崎市フェニックス自然動物園',
    name: 'フェニックス自然動物園',
    prefecture: '宮崎県',
    city: '宮崎市',
    address: '〒880-0122 宮崎県宮崎市塩路3083',
    nearest_station: 'JR日南線「木花駅」徒歩約20分',
    hours: '9:00〜17:00（入園は16:30まで）',
    closed_days: '火曜日（祝日の場合翌日）・年末年始',
    fees: '大人 820円／小中学生 410円',
    description: '南国宮崎らしくフラミンゴが放し飼い。コアラ・チンパンジー・カバなど約100種を飼育する市立動物園。',
    official_url: 'https://www.phoenix-zoo.or.jp/',
    asoview_url: null,
    hero_emoji: '🦩',
  },
  {
    slug: 'hirakawa',
    db_name: '鹿児島市平川動物公園',
    name: '平川動物公園',
    prefecture: '鹿児島県',
    city: '鹿児島市',
    address: '〒891-0133 鹿児島県鹿児島市平川町5669-1',
    nearest_station: 'JR「鹿児島中央駅」バス約50分',
    hours: '9:00〜17:00（入園は16:30まで）',
    closed_days: '水曜日（祝日の場合翌日）・年末年始',
    fees: '大人 500円／小中学生 100円',
    description: '国内唯一のコビトカバを飼育。コアラ・アジアゾウ・ホワイトタイガーなど約140種を桜島を望む立地で展示。',
    official_url: 'https://www.hirakawazoo.jp/',
    asoview_url: null,
    hero_emoji: '🦛',
  },
  {
    slug: 'tobu',
    db_name: '東武動物公園',
    name: '東武動物公園',
    prefecture: '埼玉県',
    city: '南埼玉郡宮代町',
    address: '〒345-0831 埼玉県南埼玉郡宮代町須賀110',
    nearest_station: '東武動物公園駅（東武伊勢崎線・日光線）から徒歩5分',
    hours: '10:00〜17:00（季節変動あり）',
    closed_days: '木曜日（祝日の場合は翌日）・冬季休園あり',
    fees: '大人 1,800円／小学生 600円／3歳以上 300円',
    description: 'ホワイトタイガーをはじめ約120種の動物を飼育。遊園地・プールも併設する複合レジャー施設。',
    official_url: 'https://www.tobuzoo.com/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F155350%2F',
    hero_emoji: '🐯',
  },
  {
    slug: 'okinawa-kodomo',
    db_name: '沖縄こどもの国',
    name: '沖縄こどもの国',
    prefecture: '沖縄県',
    city: '沖縄市',
    address: '〒904-0021 沖縄県沖縄市胡屋5-7-1',
    nearest_station: '沖縄バス「こどもの国前」下車すぐ',
    hours: '9:30〜18:00（入園は17:30まで）',
    closed_days: '水曜日（祝日の場合翌日）・年末年始',
    fees: '大人 500円／小中学生 200円',
    description: '亜熱帯の豊かな自然の中、オキナワイノシシ・リュウキュウイノシシなど琉球の固有種を含む約70種を飼育。',
    official_url: 'https://www.okzoo.jp/',
    asoview_url: 'https://px.a8.net/svt/ejp?a8mat=4B1KXR+740FOA+455G+BW0YB&a8ejpredirect=https%3A%2F%2Fwww.asoview.com%2Fbase%2F154568%2F',
    hero_emoji: '🌺',
  },
];

/** 都道府県別にグルーピングして返す（都道府県順を保持） */
export function groupByPrefecture(zoos) {
  const order = [];
  const map = new Map();
  for (const z of zoos) {
    if (!map.has(z.prefecture)) {
      order.push(z.prefecture);
      map.set(z.prefecture, []);
    }
    map.get(z.prefecture).push(z);
  }
  return order.map(pref => ({ prefecture: pref, zoos: map.get(pref) }));
}

/** db_name → zoo エントリの逆引き（赤ちゃんデータ突合用） */
export function zooByDbName(dbName) {
  return ZOOS.find(z => z.db_name === dbName) || null;
}

/** slug → zoo エントリ */
export function zooBySlug(slug) {
  return ZOOS.find(z => z.slug === slug) || null;
}

/** 既存 ZOO_AFFILIATE_MAP 形式で返す（後方互換） */
export function toAffiliateMap() {
  const map = {};
  for (const z of ZOOS) {
    map[z.db_name] = {
      official_url: z.official_url,
      asoview_url:  z.asoview_url,
      slug:         z.slug,
    };
  }
  return map;
}
