name = "babyanimals-worker"
main = "src/index.ts"
compatibility_date = "2024-09-01"

[vars]
SUPABASE_URL = "https://hvhpfrksyytthupboaeo.supabase.co"  # ← あなたのURLに置換

[triggers]
crons = [
  "0 * * * *",      # ニュース: 毎時
  "15 18 * * *",    # 動物園: 毎日 (JST 03:15 相当)
  "30 18 * * *"     # 赤ちゃん: 毎日 (JST 03:30 相当)
]

[observability]
enabled = true

# Secret はダッシュボード or CLI で設定してください
# wrangler secret put SUPABASE_SERVICE_ROLE
